//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafezito.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cafezito.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _181744259 {
            get {
                object obj = ResourceManager.GetObject("181744259", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _31c590546de4a3ffcd05f498cdfd066f {
            get {
                object obj = ResourceManager.GetObject("31c590546de4a3ffcd05f498cdfd066f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _644754_e069bdc718244bd4b9ef8fbce7e57268_mv2 {
            get {
                object obj = ResourceManager.GetObject("644754_e069bdc718244bd4b9ef8fbce7e57268~mv2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Captura_de_tela_2024_08_13_192308 {
            get {
                object obj = ResourceManager.GetObject("Captura de tela 2024-08-13 192308", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Desenho_De_Rysunek_Xícara_Café_E_Grãos_PNG___Desenho_De_Café__Desenho_De_Xícara_De_Café__Desenho_De_Grão_De_Café_Imagem_PNG_e_PSD_Para_Download_Gratuito {
            get {
                object obj = ResourceManager.GetObject("Desenho De Rysunek Xícara Café E Grãos PNG , Desenho De Café, Desenho De Xícara D" +
                        "e Café, Desenho De Grão De Café Imagem PNG e PSD Para Download Gratuito", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pao_2_e1611843377616 {
            get {
                object obj = ResourceManager.GetObject("pao-2-e1611843377616", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_brazilian_snack_traditional_cheese_bread_from_minas_gerais_pao_de_queijo_png_image_11711937 {
            get {
                object obj = ResourceManager.GetObject("pngtree-brazilian-snack-traditional-cheese-bread-from-minas-gerais-pao-de-queijo-" +
                        "png-image_11711937", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_brazilian_snack_traditional_cheese_bread_from_minas_gerais_pao_de_queijo_png_image_11711937__1_ {
            get {
                object obj = ResourceManager.GetObject("pngtree-brazilian-snack-traditional-cheese-bread-from-minas-gerais-pao-de-queijo-" +
                        "png-image_11711937 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Texto_do_seu_parágrafo {
            get {
                object obj = ResourceManager.GetObject("Texto do seu parágrafo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Texto_do_seu_parágrafo__1_ {
            get {
                object obj = ResourceManager.GetObject("Texto do seu parágrafo (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Texto_do_seu_parágrafo__1___1_ {
            get {
                object obj = ResourceManager.GetObject("Texto do seu parágrafo (1) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Texto_do_seu_parágrafo__1_1 {
            get {
                object obj = ResourceManager.GetObject("Texto do seu parágrafo (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Texto_do_seu_parágrafo__2___1_ {
            get {
                object obj = ResourceManager.GetObject("Texto do seu parágrafo (2) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Texto_do_seu_parágrafo__2___4_ {
            get {
                object obj = ResourceManager.GetObject("Texto do seu parágrafo (2) (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Texto_do_seu_parágrafo__2___4___1_ {
            get {
                object obj = ResourceManager.GetObject("Texto do seu parágrafo (2) (4) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Texto_do_seu_parágrafo__2___5_ {
            get {
                object obj = ResourceManager.GetObject("Texto do seu parágrafo (2) (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Texto_do_seu_parágrafo1 {
            get {
                object obj = ResourceManager.GetObject("Texto do seu parágrafo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap th {
            get {
                object obj = ResourceManager.GetObject("th", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
